author: Chormi
description: Recovers death inventories on CK.
website: https://gitlab.com/cubekrowd/plugins/deathrecovery
main: net.cubekrowd.deathrecovery.Main
version: ${project.version}
name: DeathRecovery
api-version: 1.15

commands:
   restoreinvgive:
      description: Set user's inventory to his selected death inventory.
      aliases: rig
      usage: /restoreinvgive <owner> <number> <player>
   restoreinvsee:
      description: Opens a container with user's selected death inventory.
      aliases: ris
      usage: /restoreinvsee <owner> <number>
   deaths:
      description: Shows all stored deaths for the player.
      usage: /deaths <owner>
   drteleport:
      description: Teleports player.
      usage: /drteleport <x> <y> <z> <world>

permissions:
   deathrecovery.deaths:
      description: Gives access to death command.
      default: op
   deathrecovery.restoregive:
      description: Gives access to the restore give command.
      default: op
   deathrecovery.restoresee:
      description: Gives access to the restore see command.
      default: op
   deathrecovery.drteleport:
      description: Teleports player.
      default: op
